#!/usr/bin/env python3
"""Generate RSA-2048 keypair and write deploy/docker/.env ready for Docker Compose.

Usage:
    python scripts/generate_keys.py

Requires:
    pip install cryptography   (already in pyproject.toml dev deps)
"""

from __future__ import annotations

import os
import textwrap
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa


def generate_rsa_keypair() -> tuple[str, str]:
    """Return (private_pem, public_pem) as strings."""
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
    )
    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()

    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode()

    return private_pem, public_pem


def write_env_file(private_pem: str, public_pem: str, env_path: Path) -> None:
    """Write .env file with JWT keys and sensible defaults."""
    # Indent PEM content for multi-line env var (docker compose compatible)
    private_indented = private_pem.strip()
    public_indented = public_pem.strip()

    content = textwrap.dedent(f"""\
        # Auto-generated by scripts/generate_keys.py
        # ── Database ─────────────────────────────────────────────────────────────────
        POSTGRES_PASSWORD=changeme_dev

        # ── Grafana ───────────────────────────────────────────────────────────────────
        GRAFANA_PASSWORD=admin

        # ── JWT Keys (RSA-2048) ───────────────────────────────────────────────────────
        APP_JWT_PRIVATE_KEY="{private_indented}"

        APP_JWT_PUBLIC_KEY="{public_indented}"
    """)

    env_path.write_text(content, encoding="utf-8")


def main() -> None:
    repo_root = Path(__file__).parent.parent
    env_path = repo_root / "deploy" / "docker" / ".env"

    if env_path.exists():
        overwrite = input(f"{env_path} already exists. Overwrite? [y/N] ").strip().lower()
        if overwrite != "y":
            print("Aborted.")
            return

    print("Generating RSA-2048 keypair...")
    private_pem, public_pem = generate_rsa_keypair()
    write_env_file(private_pem, public_pem, env_path)
    print(f"Written: {env_path}")
    print()
    print("Next steps:")
    print("  cd deploy/docker")
    print("  docker compose up --build")


if __name__ == "__main__":
    main()
